
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 13 21:09:23 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 29;
  public static final int CHAR = 40;
  public static final int CONST = 26;
  public static final int CONTINUE = 45;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 25;
  public static final int RPAREN = 7;
  public static final int AND = 28;
  public static final int RECORD = 44;
  public static final int LS = 33;
  public static final int OR = 31;
  public static final int BOOL = 51;
  public static final int COMMA = 8;
  public static final int CLASS = 43;
  public static final int LSE = 34;
  public static final int INC = 14;
  public static final int DIV = 24;
  public static final int PLUS = 11;
  public static final int IF = 22;
  public static final int THIS = 48;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 41;
  public static final int EQUAL = 9;
  public static final int SUPER = 47;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 49;
  public static final int DEQUAL = 17;
  public static final int MOD = 32;
  public static final int IDENT = 50;
  public static final int BREAK = 35;
  public static final int VOID = 16;
  public static final int GTE = 20;
  public static final int COLON = 15;
  public static final int LBRACE = 3;
  public static final int ELSE = 21;
  public static final int ENUM = 46;
  public static final int READ = 37;
  public static final int GOTO = 38;
  public static final int WHILE = 39;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int DEC = 13;
  public static final int GT = 36;
  public static final int DO = 42;
  public static final int PRINT = 12;
  public static final int NOTEQ = 27;
}

